### ISSUE TITLE
When doing bigger backups, always an error

### ISSUE THREAD

**Issue by iohenkies** [rmiceli/rsnapstats#5] opened 2018-03-02 08:19 UTC
Hi,

I love the script and the output, but sometimes I get an error. I'm pretty sure this happens only when the backup to make is a bit bigger. For instance after updates on a server or with a completely new server we want to backup.

Normal, smaller backups, like up to 1GB max, do not generate the error. Any ideas?

```
root@backup01:/etc/cron.d# rsnapshot -c /etc/rsnapshot/serverabc.conf hourly 2>&1 | python /root/bin/rsnapstats.py 2>&1 | mailx -s "Backup TEST serverabc" myemail@domain.com
Traceback (most recent call last):
  File "/root/bin/rsnapstats.py", line 140, in <module>
    main()
  File "/root/bin/rsnapstats.py", line 99, in main
    stats_dict['source'] = line.split()[-2].split('@')[-1]
IndexError: list index out of range
mailx: Null message body; hope that's ok
```
This error is when run from cron, but also when doing it manually, as you can see above. A subsequent error can go wrong as well, or succeed, depending on the amount of data.

When not piping to rsnapstats.py the backups always succeed.

Thanks and regards.

**Comment by rmiceli** [comment] 2018-03-02 20:48
Thanks, can you provide the rsync command(s) that rsnapshot calls when you run:

    rsnapshot -c /etc/rsnapshot/serverabc.conf hourly

**Comment by iohenkies** [comment] 2018-03-03 19:08
Yes of course. This is on Debian 9.3 FWIW with all the latest pacthes. Thanks!

This is from the log:
/usr/bin/rsync -av --stats --delete --numeric-ids --relative --delete-excluded --exclude-from=/etc/rsnapshot/myserver01.external.example.com.exclude --rsh=/usr/bin/ssh -q --link-dest=/mnt/storage/myserver01.external.example.com/hourly.1/data/ myserver01.external.example.com:/ /mnt/storage/myserver01.external.example.com/hourly.0/data/

**Comment by rmiceli** [comment] 2018-03-03 19:57
Okay, I think I see the issue. Since you are backing up the root directory "/", the executable "/usr/bin/rsync" is included in the backup and gets printed in the file list of the rsync output. When rsnapstats parses that line, it generates the same error message that you are getting. 

I just pushed 24d9bec673c939257f1c6d71c62af2b1467ea425, let me know if that fixes your issue.

**Comment by iohenkies** [comment] 2018-03-04 09:57
Awesome, I can report back when there is a lot to backup! Do you have any idea if the backups that generated this error did succeed? Is it cosmetic or really an error?

**Comment by rmiceli** [comment] 2018-03-06 11:28
The error occurs when the file /usr/bin/rsync is included in the backup. The rsync output prints this into the log, and rsnapstats.py incorrectly tries to parse that line.

The issue is resolved on my end. Let me know if this fix works for you and I will close the issue. Thanks

**Comment by iohenkies** [comment] 2018-03-06 12:36
Looking fine this far. Thanks again.

**Closed as completed** 2018-03-07 03:35 UTC
